---
version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    target-branch: master
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    target-branch: v18.04
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    target-branch: v20.04
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: master
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: v18.04
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: friday
    target-branch: v20.04
    open-pull-requests-limit: 10
